
[font]
size = 12

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 5

[general]
import = ["~/.config/alacritty/black-metal-gorgoroth.toml"]
