# Base16 Black Metal (Gorgoroth) for Alacritty
[colors.primary]
background = "0x000000" 
foreground = "0xc1c1c1" 

[colors.normal]
black   = "0x000000"
red     = "0x5f8787"
green   = "0x9b8d7f"
yellow  = "0x8c7f70"
blue    = "0x888888"
magenta = "0x999999"
cyan    = "0xaaaaaa"
white   = "0xc1c1c1"

[colors.bright]
black   = "0x121212"
red     = "0x5f8787"
green   = "0x9b8d7f"
yellow  = "0x8c7f70"
blue    = "0x888888"
magenta = "0x999999"
cyan    = "0xaaaaaa"
white   = "0xc1c1c1"

[colors.cursor]
text = "0x000000"   
cursor = "0xc1c1c1" 

